range:
  scan_range: 1.232.49.0/24
  country: US

user_agents:
  agents:
    - "Mozilla/5.0 (Windows NT 10.0)"
    - "Mozilla/5.0 (X11; Linux x86_64)"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"
    - "curl/7.68.0"
